### ISSUE TITLE
[Feat] - Mockup & HTML/Styles implementation

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/livepeer-alerts-frontend#3]
Must be:
- Clean and simple
- Responsive
- Mobile first design

Tasks:
- [x] Home page layout, welcome and T&Cs - Issue #4 
- [x] Token holder account summary - Issue #5 
- [x] Subscribe/Unsubscribe notifications - Issue #6 
- [x] E-mails templates - Issue #7 
- [x] Stop monitoring page - Issue #8
